### ISSUE TITLE
JSON Viewer

### ISSUE THREAD

**Issue by phtj** [design-automation/mobius-cesium#1]
Lets add a JSON viewer. Since our data is mostly JSON, it would be very useful for understanding the data and for debugging to be able to see the JSON as collapsible text. For large documents, I am also thinking this may also be faster than a simple text viewer. I googled around, and found this one, https://github.com/mohsen1/json-formatter-js, but I am not sure if it is the best option.

**Comment by akshatamohanty** [comment]
I added some functionality to the text viewer to render GeoJSON better. 

![image](https://user-images.githubusercontent.com/6915805/39296641-01857412-4974-11e8-8bb5-06c7182e2c5a.png)
