### ISSUE TITLE
unable to save .mob file

### ISSUE THREAD

**Issue by limyyj** [design-automation/mobius-cesium#10]
After setting global variables with geojson files of large sizes, the .mob file cannot be saved.
After setting variables with geojson files of large sizes as defaults, the .mob file also cannot be saved.
It gives a "Failed - Network error" in the downloads bar.

File sizes are: 44121, 14406 and 7756 KB
All are too big to be saved.

If they are created as normal variables, without a default value, the file can be saved fine.
The flowchart was not executed at all.

(The .mob file has the variables as normal variables without default values)
[Test files.zip](https://github.com/design-automation/mobius-cesium/files/1974250/Test.files.zip)

**Comment by akshatamohanty** [comment]
The flowchart is not executed in any case with huge files?

**Comment by limyyj** [comment]
Yes, even if you don't execute at all it can't save. As long as you choose a file (for global and default).

**Comment by akshatamohanty** [comment]
@limyyj fixed. needs to be tested

**Comment by limyyj** [comment]
Set as default and save -> ok
Set as global variable and save -> ok
- After setting as default values, opening and running file works without having to respecify the files

Saving geojson from procedure (geo.collection.save) works sometimes but not always maybe due to size also.

This is the resulting file from setting the three files as global variables and trying to save two geojson files from it. The first one (in simplify_map) fails, same network error. The second one (node3) manages to download fine.

[save_test.zip](https://github.com/design-automation/mobius-cesium/files/1978575/save_test.zip)

**Comment by akshatamohanty** [comment]
@phtj updated function for downloading files for the module functions. the other one times out if the file is too big. 

downloadContent(filestring, filename) {
   let blob = new Blob([fileString], {type: 'application/json'});
    if (window.navigator.msSaveOrOpenBlob) {
      window.navigator.msSaveOrOpenBlob(blob, filename);
    } else {
        const a = document.createElement('a');
        document.body.appendChild(a);
        const url = window.URL.createObjectURL(blob);
        a.href = url;
        a.download = filename;
        a.click();
        setTimeout(() => {
          window.URL.revokeObjectURL(url);
          document.body.removeChild(a);
        }, 0)
    }
  }
