### ISSUE TITLE
Procedure Action Buttons obstruct procedure inputs

### ISSUE THREAD

**Issue by phtj** [design-automation/mobius-cesium#21]
![image](https://user-images.githubusercontent.com/8304948/39811243-a599bfea-53ba-11e8-99ba-eba94189940a.png)

**Comment by pkered** [comment]
![image](https://user-images.githubusercontent.com/18225208/40697488-fc9141b8-63fc-11e8-9335-3ec888fbbd03.png)
Just pushed a fix.
