### ISSUE TITLE
Sidebar fonts and text unclear in viewer

### ISSUE THREAD

**Issue by akshatamohanty** [design-automation/mobius-cesium#44]
![image](https://user-images.githubusercontent.com/6915805/41703610-7f5af448-7566-11e8-956a-1c32704774a9.png)

![image](https://user-images.githubusercontent.com/6915805/41703636-99d1bfbe-7566-11e8-88ec-3624bc10b9e9.png)

**Comment by pkered** [comment]
![image](https://user-images.githubusercontent.com/18225208/41754587-7f3fbb0c-7605-11e8-83df-43877310ee66.png)

Changing the background opacity to 0.8/0.9 works well for all maps (0.9 here)
Font color was changed to a brighter grey: #D3D3D3
slider bar colors are variables $color2 #8AA8C0 and$color4 #F0BFA0
